version: '3'
# ref: 
# https://docs.docker.com/compose/compose-file/

services: 
    ###########
    # PHP-FPM #
    ###########
    php: 
        build: .docker/df/phpfpm
            args:
                servername: "my.url_website"
                buildno: 1
        restart: always
        working_dir: /var/www
        ports: 
            - 9000:9000
        environment:
            - DB_USER=user
            - DB_PASS=pass
        volumes:
            - ${DIRECTORY}:/var/www/
            - ${DIRECTORY}/.docker/config/phpfpm/:/etc/php/7.4/:ro
           # - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/mods-available/:/etc/php/7.4/fpm/conf.d/
           # - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/mods-available/:/etc/php/7.4/cli/conf.d/
        
            # home
            - ${DIRECTORY}/.docker/home:/root:ro
            
            # sqlite
            - ${DIRECTORY}/.docker/.data/sqlite/:/sqlite/
        networks: 
            - phpext
    
networks: 
    phpext: