version: '3'

services: 
    phpfpm: 
        build: .docker/df/phpfpm
        restart: always
        working_dir: /appli
        ports: 
            - 9001:9000
        environment:
            - DB_USER=user
            - DB_PASS=pass
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/phpfpm/:/etc/php/7.4/:ro
            
            # ################
            # Use git autocompletion and prompt
            # from https://github.com/git/git/blob/master/contrib/completion/
            # git-completion.bash
            # git-prompt.sh
            # ################
            - ${WEBSERVER}/${DIRECTORY}/.docker/.phpfpm/home:/root
        networks: 
            - phpext
    
networks: 
    phpext:
        driver: bridge

# https://devilbox.org
# https://nanobox.io

# https://laradock.io/
# https://github.com/laraedit/laraedit-docker
# https://laragon.org/
# https://www.easyphp.org/

######################