version: '2.2'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            - ${WEBSERVER}/${DIRECTORY}/.docker/conf/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        ports:
            - 89:80
        networks: 
            - ext
          
    phpfpm: 
        image: phpexttry:latest
        #build: .docker/conf/fpm
        restart: always
        working_dir: /appli
        ports: 
            - 9009:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            #- ${WEBSERVER}/${DIRECTORY}/.docker/conf/fpm/php.ini:/etc/php/7.3/fpm/php.ini
        networks: 
            - ext
    
    # mariadb: 
    #     image: mariadb
    #     container_name: mariadb
    #     ports: 
    #         - 3306:3306
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: example
        # volumes: 
        #     - /WEBSERVER/packages/data:/var/lib/mysql
    
    # adminer:
    #     image: adminer
    #     container_name: mariadb-adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     - type: volume
    #     source: mydata
    #     target: /data
    #     volume:
    #       nocopy: true
    #   - type: bind
    #     source: ./static
    #     target: /opt/app/static
       
networks: 
    ext:
        driver: bridge

#################
# https://min.io
#################
#     image: minio/minio
#     ports:
#         - 9999:9000

######################
# https://nanobox.io
# https://devilbox.org
######################