version: '3'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        volumes:
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ${WEBSERVER}/${DIRECTORY}:/var/www/
        ports:
            - 8001:80
        networks: 
            - phpext

    # SECOND SERVER TO TRY LOAD BALANCING

    nginx2:
        image: nginx:1.17
        restart: always
        volumes:
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${WEBSERVER}/${DIRECTORY}/.docker/config/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ${WEBSERVER}/${DIRECTORY}:/var/www/
        ports:
            - 8002:80
        networks: 
            - phpext

    apache:
        image: httpd:2.4
        restart: always
        ports: 
            - 8003:80
        volumes:
            - ${WEBSERVER}/${DIRECTORY}.docker/config/apache-httpd/:/usr/local/apache2/conf/:ro
            - ${WEBSERVER}/${DIRECTORY}:/usr/local/apache2/htdocs/
        networks:
            - phpext
    
    # todo!
    
    # lighttpd:
    #     image: sebp/lighttpd
    #     restart: always
    #     ports: 
    #         - 89:80
    #     volumes: 
    #         - /TMAID/.docker/conf/lighttpd/:/etc/lighttpd/:ro
    #         - /TMAID/:/var/www/localhost/htdocs/
    #     tty: true
    #     networks:
    #         - phpext
          
networks: 
    phpext:
        