version: '3'
# ref: 
# https://docs.docker.com/compose/compose-file/

services: 
    ###########
    # PHP-FPM #
    ###########
    php: 
        build: .docker/fpm
        working_dir: /var/www
        volumes:
            - ${DIRECTORY}:/var/www/
            - ${DIRECTORY}/.docker/config/phpfpm/:/etc/php/7.4/:ro

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
        # For Windows users
        command: "--innodb_use_native_aio=0"
        volumes:
           - ${DIRECTORY}/.docker/config/mysql/my.cnf:/etc/mysql/my.cnf:ro

        networks: 
            - phpext
    
networks: 
    phpext: