version: '3'
# ref: 
# https://docs.docker.com/compose/compose-file/

services: 
    ###########
    # PHP-FPM #
    ###########
    php: 
        build: .docker
        volumes:
            - ${DIRECTORY}:/var/www/
            - ${DIRECTORY}/.docker/php:/etc/php/7.4/cli
        networks: 
            - phpext

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
        volumes:
            - ${DIRECTORY}/.docker/my.cnf:/etc/mysql/my.cnf:ro
            - mysql:/var/lib/mysql
        networks: 
            - phpext
    
networks: 
    phpext:
    
volumes:
    mysql:
