version: '3'

services: 
    nginx:
        image: nginx:1.17
        container_name: nginx89
        restart: always
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            - ${WEBSERVER}/${DIRECTORY}/.docker/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        ports:
            - 89:80
        networks: 
            - ext
          
    phpfpm: 
        image: phpexttry:latest #from phpdockerio/php73-fpm:latest
        #build: .docker/conf/fpm
        container_name: phpfpm89
        restart: always
        working_dir: /appli
        ports: 
            - 9009:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            #- ${WEBSERVER}/${DIRECTORY}/.docker/fpm/php.ini:/etc/php/7.3/fpm/php.ini
        networks: 
            - ext
    
    selenium:
        image: nkovacs/selenium-standalone-phantomjs:latest
        container_name: selenium89
        restart: always
        ports:
            - 4444:4444
            - 5900:5900
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
        networks: 
            - ext

    # mysql:
    #     image: mysql:5.7
    #     container_name: mysql89
    #     #restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: pass
    #         #MYSQL_DATABASE: db
    #     volumes:
    #         - ${WEBSERVER}/${DIRECTORY}/data:/var/lib/mysql
    #     command: /bin/bash -c "mysqld --user=root --innodb-use-native-aio=0"
    #     networks: 
    #         - ext
    
    # mariadb: 
    #     image: mariadb
    #     container_name: mariadb
    #     ports: 
    #         - 3306:3306
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: example
        # volumes: 
        #     - /WEBSERVER/packages/data:/var/lib/mysql
    
    # adminer:
    #     image: adminer
    #     container_name: mariadb-adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     - type: volume
    #     source: mydata
    #     target: /data
    #     volume:
    #       nocopy: true
    #   - type: bind
    #     source: ./static
    #     target: /opt/app/static
       
networks: 
    ext:
        driver: bridge

#################
# https://min.io
#################
#     image: minio/minio
#     ports:
#         - 9999:9000
######################

# https://devilbox.org
# https://nanobox.io

# https://laradock.io/
# https://github.com/laraedit/laraedit-docker
# https://laragon.org/
# https://www.easyphp.org/

######################