version: '2.2'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            - ${WEBSERVER}/${DIRECTORY}/.docker/conf/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        ports:
            - 89:80
        networks: 
            - ext
          
    phpfpm: 
        build: .docker/conf/fpm
        restart: always
        working_dir: /appli
        ports: 
            - 9009:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            #- ${WEBSERVER}/${DIRECTORY}/.docker/conf/fpm/php.ini:/etc/php/7.3/fpm/php.ini
        networks: 
            - ext
       
networks: 
    ext:
        driver: bridge