version: '3.4'

services: 
    php: 
        build: .
        volumes:
            - /WEBSERVER/phpext-sample/.docker/extensions.ini:/etc/php/7.4/cli/conf.d/extensions.ini:ro
            - /WEBSERVER/phpext-sample:/var/www/

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
        volumes:
            - /WEBSERVER/phpext-sample/.docker/my.cnf:/etc/mysql/my.cnf:ro
            - mysql:/var/lib/mysql
    
volumes:
    mysql:
