version: '3'

services: 
    nginx81:
        image: nginx:1.17
        restart: always
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            - ${WEBSERVER}/${DIRECTORY}/.docker/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm81
        ports:
            - 81:80
        networks: 
            - ext1
          
    phpfpm81: 
        #image: phpexttry:latest #from phpdockerio/php73-fpm:latest
        build: .docker/fpm
        container_name: phpfpm81
        restart: always
        working_dir: /appli
        depends_on: 
            - mysql81
        ports: 
            - 9001:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/appli
            #- ${WEBSERVER}/${DIRECTORY}/.docker/fpm/php.ini:/etc/php/7.3/fpm/php.ini
            
            # ################
            # from https://github.com/git/git/blob/master/contrib/completion/
            # ################
            - ${WEBSERVER}/${DIRECTORY}/.docker/fpm/home:/root
        networks: 
            - ext1
    
    # selenium89:
    #     image: nkovacs/selenium-standalone-phantomjs:latest
    #     container_name: selenium89
    #     restart: always
    #     ports:
    #         - 4444:4444
    #         - 5900:5900
    #     volumes:
    #         - ${WEBSERVER}/${DIRECTORY}:/appli
    #     networks: 
    #         - ext1

    # issue 
    # https://stackoverflow.com/questions/48239668/fails-to-initialize-mysql-database-on-windows-10
    mysql81:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: db
        command: "--innodb_use_native_aio=0"
        #command: /bin/bash -c "mysqld --user=root --initialize --innodb-use-native-aio=0" #first time --initialize(-insecure)
        #command: /bin/bash -c "mysqld --innodb-use-native-aio=0" #remove for next

        volumes:
            - ${WEBSERVER}/${DIRECTORY}/data/mysql:/var/lib/mysql
        #  - ${WEBSERVER}/${DIRECTORY}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        ports:
            - 3306:3306
        networks: 
            - ext1

    ######
    # Git
    ######
    git81:
        image: jkarlos/git-server-docker
        restart: always
        ports:
            - '2222:22'
        volumes: 
            - ${WEBSERVER}/${DIRECTORY}/.git-server/keys:/git-server/keys
            - ${WEBSERVER}/${DIRECTORY}/.git-server/repos:/git-server/repos

        networks: 
            - ext1
    
networks: 
    ext1:
        driver: bridge


    # mariadb81: 
    #     image: mariadb
    #     container_name: mariadb
    #     ports: 
    #         - 3308:3306
    #     environment:
    #         MYSQL_ROOT_PASSWORD: example
    #     volumes: 
    #         - ${WEBSERVER}/${DIRECTORY}/data/maria:/var/lib/mysql
        # networks: 
        #     - ext1
    
    # adminer81:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     - type: volume
    #     source: mydata
    #     target: /data
    #     volume:
    #       nocopy: true
    #      - type: bind
    #     source: ./static
    #     target: /opt/app/static

    ######################
    # GIT SERVER
    # jkarlos/git-server-docker
    ######################
       


#################
# https://min.io
#################
#     image: minio/minio
#     ports:
#         - 9999:9000
######################

# https://devilbox.org
# https://nanobox.io

# https://laradock.io/
# https://github.com/laraedit/laraedit-docker
# https://laragon.org/
# https://www.easyphp.org/

######################