version: '2.2'

services: 
    nginx:
        image: nginx:1.17
        restart: always
        #container_name: nginx
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/usr/share/nginx/html
            - ${WEBSERVER}/${DIRECTORY}/.docker/conf/nginx:/etc/nginx/conf.d:ro
        depends_on: 
            - phpfpm
        ports:
            - 80:80
        networks: 
            - ext
          
    phpfpm: 
        build: .docker/conf/fpm
        restart: always
        #container_name: phpfpm
        working_dir: /usr/share/nginx/html
        ports: 
            - 9000:9000
        volumes:
            - ${WEBSERVER}/${DIRECTORY}:/usr/share/nginx/html
        networks: 
            - ext
       
networks: 
    ext:
        driver: bridge