version: '2.4'

################################ not functional on windows, todo!

services:
    traefik:
        image: stefanscherer/traefik-windows
        command: --docker.endpoint=npipe:////./pipe/docker_engine --logLevel=DEBUG
        ports:
        - "8080:8080" # Please read: https://docs.traefik.io/configuration/api/#security
        - "443:443"
        - "80:80"
        isolation: process # workaround for https://github.com/containous/traefik/issues/4409
        volumes:
        - .:C:/etc/traefik
        - type: npipe
            source: \\.\pipe\docker_engine
            target: \\.\pipe\docker_engine
        networks: 
            phpext:

    whoami1:
        image: stefanscherer/whoami
        labels:
        - "traefik.backend=whoami"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:whoami.docker.local"
        networks: 
            phpext:

    whoami2:
        image: stefanscherer/whoami
        labels:
        - "traefik.backend=whoami"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:whoami.docker.local"
        networks: 
            phpext:

#  portainer:
#    image: portainer/portainer
#    labels:
#      - "traefik.backend=portainer"
#      - "traefik.frontend.rule=Host:portainer.yourdomain.com"

networks:
    phpext:
      