<?php

namespace Auth;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-06-18 at 18:23:31.
 */
class AuthTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Index
     */
    protected $index;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->index = new Index;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {}

    public function testBasic() 
    {
        $_SERVER['PHP_AUTH_USER'] = 'user';
        $_SERVER['PHP_AUTH_PW'] = 'pass';
        $_SESSION['delai'] = time();
        $this->index->index();
        $this->expectOutputRegex('/auth ok/');
    }

    public function testDigest() 
    {
        $digest = new Digest;

        $_SERVER['PHP_AUTH_DIGEST'] = $digest->getDigestHeader();
        $_SESSION['delai'] = time();

        $this->index->digestAction($digest);
        $this->expectOutputRegex('/digest ok/');
    }
}