<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-06-18 at 18:23:31.
 */
class IconvTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Index
     */
    protected $manager;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Iconv\Iconv;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {}

    public function testIconv() 
    {
        $this->object->test();
        $this->assertTrue(true);
    }
}
