<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-06-18 at 18:23:31.
 */
class IteratorsTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Index
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->i = new \Iterator\Index;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }



    /************************************classiques  */
    public function testArrays()
    {
        $this->i->arrays(['michel','flush']);
        $this->expectOutputRegex('/michel/');
    }

    
    public function testAggregate()
    {
        $this->i->aggregate();
        $this->expectOutputRegex('/012340/');
    }

    public function testIterIter()
    {
        $this->i->iterIter();
        $this->expectOutputRegex('/deliplussatirplus/');
    }

    /**
     * @covers Iterator\Index::directory
     * @todo   Implement testDirectory().
     */
    public function testDirectory()
    {
        $this->i->directory();
        $this->expectOutputRegex('/Iterator/');
    }

    public function testLogFilter()
    {
        $this->i->logFilter();
        $this->expectOutputRegex('/10.21.510.6 10.21.510.9 /');
    }

    





    /******************************recursives */

}
