<?php

namespace Socket;

use RuntimeException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-06-18 at 18:23:31.
 */
class SocketTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Index
     */
    protected $index;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->index = new Index;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {}

    /**
     * @depends testServer
     */
    public function testClient() 
    {
        echo 'c';
    }

    public function testServer() 
    {
        echo 's';
    }

    public function tryLaunchServerAndCatchResponse()
    {
        $sock = socket_create(AF_INET, SOCK_STREAM, 0);
        if(!socket_bind($sock, 'localhost', 0)) throw new RuntimeException('Couldnt bind');
        socket_listen($sock);

        $client = socket_accept($sock);
        $input = socket_read($client, 1024);

        echo $input;
    }
}