version: "3"

services:
    ################
    # PROXY - CACHE
    ################
    haproxy:
        image: haproxy:2.2
        restart: always
        networks:
            - web

    varnish: 
        image: varnish:6.0
        restart: always
        networks:
            - web

networks: 
    web:
        external: true
