version: "3"

services:
    ###############
    # PHP-FPM
    ################
    fpm:
        build: .docker/Df/fpm 
        restart: always
        environment:
            MYSQL_URL: mysql:host=mysql;port=3306;dbname=mydb
            MARIADB_URL: mysql:host=mariadb;port=3307;dbname=madb
            MYSQL8_URL: mysql:host=mysql8;port=3306;dbname=my8db
            POSTGRES_URL: pgsql:host=postgres;port=5432;dbname=pgdb
            SQLITE_URL: sqlite:/sqlite/sqdb.sqlite
            DB_USER: user
            DB_PASS: pass
        ports:
            - 9000:9000
            - 12312:12312
        volumes: 
            # php
            - /TMAID/.docker/conf/phpfpm/:/etc/php/7.4/
            - /TMAID/.docker/conf/phpfpm/mods-available/:/etc/php/7.4/fpm/conf.d/
            - /TMAID/.docker/conf/phpfpm/mods-available/:/etc/php/7.4/cli/conf.d/

            # working dir
            - /TMAID/:/var/www/

            # sqlite
            - /TMAID/.docker/.data/sqlite/:/sqlite/
        
            # git & home for .bash_rc
            - /TMAID/.docker/conf/git/.gitconfig:/root/.gitconfig:ro
            - /TMAID/.docker/.home/:/root/
        working_dir: /var/www
        networks:
            - web
    
    # for api-tools
    fpm-api:
        build: .docker/Df/fpm 
        restart: always
        ports:
            - 9001:9000
        volumes:         
            - /TMAID/api:/var/www_api/
        working_dir: /var/www_api
        networks:
            - web

    #ruby:
    #    image: ruby
    
# docker network create web
networks: 
    web:
        external: true
