version: "3"

services:
    
    ############ ADMIN ###########
    phpmyadmin:
        image: phpmyadmin:5.0
        restart: always
        ports: 
            - 8080:80
        environment: 
            - PMA_ARBITRARY=1
        external_links:
            - mariadb:mariadb
            - mysql:mysql
        networks:
            - web

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        networks:
            - web

    pgadmin:
        image: dpage/pgadmin4:4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@localhost.fr
            - PGADMIN_DEFAULT_PASSWORD=pass
        ports: 
            - 8082:80
        networks:
            - web

    #######
    # SQLITE admin: https://www.phpliteadmin.org
    # into phpfpm container
    #######

    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        restart: always
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_NAME=redis
        ports: 
            - 8083:80
        networks:
            - web

    memcachedadmin:
        image: jacksoncage/phpmemcachedadmin
        restart: always
        ports:
            - 8084:80
        networks:
            - web

networks: 
    web:
        external: true
