name: PHPext

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

     # Php ext
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        extensions: intl, mbstring

    - name: Run test suite
      run: |
        sudo chmod 777 ./phpunit
        sudo make tests
