<?php

namespace Phpext\tests\Php;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-06-18 at 18:23:31.
 */
class StreamTest extends TestCase
{
    /**
     * @var Index
     */
    protected $index;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->index = new Index;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {}

    public function testFilter() 
    {
        $this->index->filter("Plusieurs stars sont passées par là");
        $this->expectOutputRegex("/Plusieurs \*{5} sont passées par là/");
    }

    public function testWrapper() 
    {
        $this->index->wrapper("once upon a ", "time");
        $this->expectOutputRegex("/AddStream: once upon a AddStream: time/");
    }

    public function testWrapper2() 
    {
        $this->index->wrapperTwo(450,251);
        $this->expectOutputRegex("/701/");
    }
}